on:
  schedule:
    - cron: 0 3 * * 6
  pull_request:
    types: [opened, reopened, closed]
  repository_dispatch:
    types: [update-deps]

name: Update dependencies

env:
  GITHUB_ACTION: 1
  TRAVIS_BUILD_DIR: ${{ github.workspace }}

jobs:
  update:
    name: Update dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: technote-space/auto-cancel-redundant-job@v1
        with:
          EXCLUDE_MERGED: 'true'
      - name: Update dependencies
        uses: technote-space/create-pr-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          EXECUTE_COMMANDS: |
            composer packages
          COMMIT_MESSAGE: 'chore: update dependencies'
          PR_DEFAULT_BRANCH_PREFIX: release/
          PR_DEFAULT_BRANCH_NAME: next-${CURRENT_VERSION}
          PR_DEFAULT_BRANCH_TITLE: 'feat: release'
          TARGET_BRANCH_PREFIX: release/
          AUTO_MERGE_THRESHOLD_DAYS: 14
